/* This puts the koans in the desired order */

jshero.koans.initReorder(
    [
    'var',
    'var2',
    'function',
    'function2',
    'functioncall',
    'parameter',
    'string',
    'stringlength',
    'stringupper',
    'stringcharat',
    'trim',
    'number',
    'modulo',
    'mean',
    'math',
    'pi',
    'round',
    'bool',
    'xor',
    'equals',
    'equals2',
    'greaterthan',
    'if',
    'array',
    'array2',
    'array3',
    'arraylength',
    'arraysort',
    'for',
    'for2',
    'further'
    ]
);
